@startuml ddd-module
package "Bootstrap" #LightGreen
package "Adapter"  {
    package "web" {
    }
    package "mobile" {
    }
}
package "Facade" {
    package "api" {
    }
    package "dto" {
    }
}
package "Application" #LightBlue {
    package "validator" #LightBlue{
    }
    package "converter" #LightBlue{
    }
    package "applicationservice" #LightBlue{
    }
    package "command" #LightBlue{
    }
}
package "Domain" #Gold {
    package "model" #Gold{
    }
    package "event" #Gold{
    }
    package "factory" #Gold{
    }
    package "repository" #Gold{
    }
    package "domainservice" #Gold{
    }
}
package "Infrastructure" #PaleGoldenRod {
    package "ACL" #PaleGoldenRod{
    }
    package "DAL" #PaleGoldenRod{
    }
    package "Integration" #PaleGoldenRod{
    }
}

skinparam package {
    ' borderColor white
}

ACL -up-> Integration
ACL -up-> DAL

Domain ..left..> Facade
Application -down-> Domain
Infrastructure -up-> Domain
Adapter -down-> Application
Application -left-> Facade
Application -down-> Infrastructure
Bootstrap -right-> Adapter
@enduml