@startuml

class DomainEvent {
  + String eventId
  + String source
  + long timestamp
  + Object data
}

class EventHandler {
  + boolean canHandle(Object event);
  + void handle(Object event);
}

class DomainEventDispatcher {
 + void publish(DomainEvent event)
 + void register(EventHandler handler)
}

class DomainEventStore

DomainEventDispatcher -down-> DomainEventStore: save
DomainEventDispatcher <-up- DomainEventStore: get

DomainEventDispatcher -up-* EventHandler: register

DomainEventDispatcher ---> DomainEvent: Publish

EventHandler --> DomainEvent: handle

@enduml